### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by sunete** [dieghernan/algolia-jekyll-action#1]
Hello! I have deployed algolia-jekyll-action on my Jekyll blog. Initially, it worked well, but today I received an Error notice.

```
Bundled gems are installed into `./vendor/bundle`
LoadError: libffi.so.6: cannot open shared object file: No such file or directory - /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/ffi-1.14.2/lib/ffi_c.so
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/ffi-1.14.2/lib/ffi.rb:6:in `require'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `require'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<top (required)>'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/sassc-2.4.0/lib/sassc.rb:31:in `<top (required)>'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `require'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `require'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/jekyll-4.2.0/lib/jekyll.rb:195:in `require'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/jekyll-4.2.0/lib/jekyll.rb:195:in `<top (required)>'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/jekyll-4.2.0/exe/jekyll:8:in `require'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/gems/jekyll-4.2.0/exe/jekyll:8:in `<top (required)>'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/bin/jekyll:23:in `load'
  /home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/bin/jekyll:23:in `<top (required)>'
bundler: failed to load command: jekyll (/home/runner/work/sunete.github.io/sunete.github.io/vendor/bundle/bin/jekyll)
Error: Process completed with exit code 1.
```

This is the Error action: <https://github.com/sunete/sunete.github.io/actions/runs/617406306>

I don't know why the error happened or how to resolve it. Please do me a favor, thanks!

**Comment by dieghernan** [comment]
Hi! I think the error came from one of your `gem`, not the action itself as it is working on the rest of my repos.

I tried this modification of your Gemfile [succesfully](https://github.com/dieghernan/remote/runs/2022051970?check_suite_focus=true), can check?

```
source "https://rubygems.org"
#source "https://gems.ruby-china.com/"
gem 'github-pages', group: :jekyll_plugins	

gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem "minimal-mistakes-jekyll"
gem 'tzinfo-data', platforms: [:x64_mingw, :mingw, :mswin]
gem 'font-awesome-sass'

group :jekyll_plugins do
  gem 'jekyll-archives'
  gem 'jemoji'
  gem 'jekyll-algolia', '~> 1.0'
  gem 'jekyll-github-metadata'
end

```

**Comment by sunete** [comment]
Thanks for your help! The error has been resolved perfectly.

https://github.com/sunete/sunete.github.io/actions/runs/617601241
